name: Math-Project-Stats

on: [push]

jobs:
  inventory:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Project Summary
        run: |
          echo "--- Layihə Hesabatı ---"
          echo "Layihə adı: Project1"
          echo "-----------------------"
          
      - name: Count test files
        run: |
          echo "Layihədəki bütün faylların siyahısı:"
          ls -R
          echo "-----------------------"
          echo "Tapılan PDF testlərinin sayı:"
          find . -maxdepth 1 -iname "*.pdf" | wc -l        
